/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as CalculadorasRouteImport } from './routes/calculadoras'
import { Route as CalculadoraMorarSozinhoRouteImport } from './routes/calculadora-morar-sozinho'
import { Route as CalculadoraCustoPetRouteImport } from './routes/calculadora-custo-pet'
import { Route as CalculadoraCustoMudancaRouteImport } from './routes/calculadora-custo-mudanca'
import { Route as CalculadoraCustoCarroRouteImport } from './routes/calculadora-custo-carro'
import { Route as CalculadoraContaDeLuzRouteImport } from './routes/calculadora-conta-de-luz'
import { Route as CalculadoraAssinaturasRouteImport } from './routes/calculadora-assinaturas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompararStreamingRouteImport } from './routes/comparar/streaming'
import { Route as CompararMudancaRouteImport } from './routes/comparar/mudanca'
import { Route as CompararEnergiaRouteImport } from './routes/comparar/energia'
import { Route as CompararAcademiaRouteImport } from './routes/comparar/academia'
import { Route as BlogQuantoCustaTerCarroRouteImport } from './routes/blog/quanto-custa-ter-carro'
import { Route as BlogQuantoCustaMorarSozinhoRouteImport } from './routes/blog/quanto-custa-morar-sozinho'
import { Route as BlogCustoPetAnualRouteImport } from './routes/blog/custo-pet-anual'
import { Route as BlogComoEconomizarContaDeLuzRouteImport } from './routes/blog/como-economizar-conta-de-luz'
import { Route as BlogAssinaturasQueValemAPenaRouteImport } from './routes/blog/assinaturas-que-valem-a-pena'
import { Route as ApiVehicleEfficiencyRouteImport } from './routes/api.vehicle-efficiency'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiFuelPricesRouteImport } from './routes/api.fuel-prices'
import { Route as ApiEnergyTariffsRouteImport } from './routes/api.energy-tariffs'
import { Route as ApiPublicDataSourcesRouteImport } from './routes/api.public-data.sources'
import { Route as ApiLocationsStatesRouteImport } from './routes/api.locations.states'
import { Route as ApiLocationsCitiesRouteImport } from './routes/api.locations.cities'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasRoute = CalculadorasRouteImport.update({
  id: '/calculadoras',
  path: '/calculadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraMorarSozinhoRoute = CalculadoraMorarSozinhoRouteImport.update({
  id: '/calculadora-morar-sozinho',
  path: '/calculadora-morar-sozinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraCustoPetRoute = CalculadoraCustoPetRouteImport.update({
  id: '/calculadora-custo-pet',
  path: '/calculadora-custo-pet',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraCustoMudancaRoute = CalculadoraCustoMudancaRouteImport.update({
  id: '/calculadora-custo-mudanca',
  path: '/calculadora-custo-mudanca',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraCustoCarroRoute = CalculadoraCustoCarroRouteImport.update({
  id: '/calculadora-custo-carro',
  path: '/calculadora-custo-carro',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraContaDeLuzRoute = CalculadoraContaDeLuzRouteImport.update({
  id: '/calculadora-conta-de-luz',
  path: '/calculadora-conta-de-luz',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraAssinaturasRoute = CalculadoraAssinaturasRouteImport.update({
  id: '/calculadora-assinaturas',
  path: '/calculadora-assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararStreamingRoute = CompararStreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => CompararRoute,
} as any)
const CompararMudancaRoute = CompararMudancaRouteImport.update({
  id: '/mudanca',
  path: '/mudanca',
  getParentRoute: () => CompararRoute,
} as any)
const CompararEnergiaRoute = CompararEnergiaRouteImport.update({
  id: '/energia',
  path: '/energia',
  getParentRoute: () => CompararRoute,
} as any)
const CompararAcademiaRoute = CompararAcademiaRouteImport.update({
  id: '/academia',
  path: '/academia',
  getParentRoute: () => CompararRoute,
} as any)
const BlogQuantoCustaTerCarroRoute = BlogQuantoCustaTerCarroRouteImport.update({
  id: '/blog/quanto-custa-ter-carro',
  path: '/blog/quanto-custa-ter-carro',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogQuantoCustaMorarSozinhoRoute =
  BlogQuantoCustaMorarSozinhoRouteImport.update({
    id: '/blog/quanto-custa-morar-sozinho',
    path: '/blog/quanto-custa-morar-sozinho',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCustoPetAnualRoute = BlogCustoPetAnualRouteImport.update({
  id: '/blog/custo-pet-anual',
  path: '/blog/custo-pet-anual',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogComoEconomizarContaDeLuzRoute =
  BlogComoEconomizarContaDeLuzRouteImport.update({
    id: '/blog/como-economizar-conta-de-luz',
    path: '/blog/como-economizar-conta-de-luz',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogAssinaturasQueValemAPenaRoute =
  BlogAssinaturasQueValemAPenaRouteImport.update({
    id: '/blog/assinaturas-que-valem-a-pena',
    path: '/blog/assinaturas-que-valem-a-pena',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiVehicleEfficiencyRoute = ApiVehicleEfficiencyRouteImport.update({
  id: '/api/vehicle-efficiency',
  path: '/api/vehicle-efficiency',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFuelPricesRoute = ApiFuelPricesRouteImport.update({
  id: '/api/fuel-prices',
  path: '/api/fuel-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnergyTariffsRoute = ApiEnergyTariffsRouteImport.update({
  id: '/api/energy-tariffs',
  path: '/api/energy-tariffs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDataSourcesRoute = ApiPublicDataSourcesRouteImport.update({
  id: '/api/public-data/sources',
  path: '/api/public-data/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationsStatesRoute = ApiLocationsStatesRouteImport.update({
  id: '/api/locations/states',
  path: '/api/locations/states',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationsCitiesRoute = ApiLocationsCitiesRouteImport.update({
  id: '/api/locations/cities',
  path: '/api/locations/cities',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculadora-assinaturas': typeof CalculadoraAssinaturasRoute
  '/calculadora-conta-de-luz': typeof CalculadoraContaDeLuzRoute
  '/calculadora-custo-carro': typeof CalculadoraCustoCarroRoute
  '/calculadora-custo-mudanca': typeof CalculadoraCustoMudancaRoute
  '/calculadora-custo-pet': typeof CalculadoraCustoPetRoute
  '/calculadora-morar-sozinho': typeof CalculadoraMorarSozinhoRoute
  '/calculadoras': typeof CalculadorasRoute
  '/comparar': typeof CompararRouteWithChildren
  '/contato': typeof ContatoRoute
  '/metodologia': typeof MetodologiaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/api/energy-tariffs': typeof ApiEnergyTariffsRoute
  '/api/fuel-prices': typeof ApiFuelPricesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/vehicle-efficiency': typeof ApiVehicleEfficiencyRoute
  '/blog/assinaturas-que-valem-a-pena': typeof BlogAssinaturasQueValemAPenaRoute
  '/blog/como-economizar-conta-de-luz': typeof BlogComoEconomizarContaDeLuzRoute
  '/blog/custo-pet-anual': typeof BlogCustoPetAnualRoute
  '/blog/quanto-custa-morar-sozinho': typeof BlogQuantoCustaMorarSozinhoRoute
  '/blog/quanto-custa-ter-carro': typeof BlogQuantoCustaTerCarroRoute
  '/comparar/academia': typeof CompararAcademiaRoute
  '/comparar/energia': typeof CompararEnergiaRoute
  '/comparar/mudanca': typeof CompararMudancaRoute
  '/comparar/streaming': typeof CompararStreamingRoute
  '/api/locations/cities': typeof ApiLocationsCitiesRoute
  '/api/locations/states': typeof ApiLocationsStatesRoute
  '/api/public-data/sources': typeof ApiPublicDataSourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculadora-assinaturas': typeof CalculadoraAssinaturasRoute
  '/calculadora-conta-de-luz': typeof CalculadoraContaDeLuzRoute
  '/calculadora-custo-carro': typeof CalculadoraCustoCarroRoute
  '/calculadora-custo-mudanca': typeof CalculadoraCustoMudancaRoute
  '/calculadora-custo-pet': typeof CalculadoraCustoPetRoute
  '/calculadora-morar-sozinho': typeof CalculadoraMorarSozinhoRoute
  '/calculadoras': typeof CalculadorasRoute
  '/comparar': typeof CompararRouteWithChildren
  '/contato': typeof ContatoRoute
  '/metodologia': typeof MetodologiaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/api/energy-tariffs': typeof ApiEnergyTariffsRoute
  '/api/fuel-prices': typeof ApiFuelPricesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/vehicle-efficiency': typeof ApiVehicleEfficiencyRoute
  '/blog/assinaturas-que-valem-a-pena': typeof BlogAssinaturasQueValemAPenaRoute
  '/blog/como-economizar-conta-de-luz': typeof BlogComoEconomizarContaDeLuzRoute
  '/blog/custo-pet-anual': typeof BlogCustoPetAnualRoute
  '/blog/quanto-custa-morar-sozinho': typeof BlogQuantoCustaMorarSozinhoRoute
  '/blog/quanto-custa-ter-carro': typeof BlogQuantoCustaTerCarroRoute
  '/comparar/academia': typeof CompararAcademiaRoute
  '/comparar/energia': typeof CompararEnergiaRoute
  '/comparar/mudanca': typeof CompararMudancaRoute
  '/comparar/streaming': typeof CompararStreamingRoute
  '/api/locations/cities': typeof ApiLocationsCitiesRoute
  '/api/locations/states': typeof ApiLocationsStatesRoute
  '/api/public-data/sources': typeof ApiPublicDataSourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculadora-assinaturas': typeof CalculadoraAssinaturasRoute
  '/calculadora-conta-de-luz': typeof CalculadoraContaDeLuzRoute
  '/calculadora-custo-carro': typeof CalculadoraCustoCarroRoute
  '/calculadora-custo-mudanca': typeof CalculadoraCustoMudancaRoute
  '/calculadora-custo-pet': typeof CalculadoraCustoPetRoute
  '/calculadora-morar-sozinho': typeof CalculadoraMorarSozinhoRoute
  '/calculadoras': typeof CalculadorasRoute
  '/comparar': typeof CompararRouteWithChildren
  '/contato': typeof ContatoRoute
  '/metodologia': typeof MetodologiaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/api/energy-tariffs': typeof ApiEnergyTariffsRoute
  '/api/fuel-prices': typeof ApiFuelPricesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/vehicle-efficiency': typeof ApiVehicleEfficiencyRoute
  '/blog/assinaturas-que-valem-a-pena': typeof BlogAssinaturasQueValemAPenaRoute
  '/blog/como-economizar-conta-de-luz': typeof BlogComoEconomizarContaDeLuzRoute
  '/blog/custo-pet-anual': typeof BlogCustoPetAnualRoute
  '/blog/quanto-custa-morar-sozinho': typeof BlogQuantoCustaMorarSozinhoRoute
  '/blog/quanto-custa-ter-carro': typeof BlogQuantoCustaTerCarroRoute
  '/comparar/academia': typeof CompararAcademiaRoute
  '/comparar/energia': typeof CompararEnergiaRoute
  '/comparar/mudanca': typeof CompararMudancaRoute
  '/comparar/streaming': typeof CompararStreamingRoute
  '/api/locations/cities': typeof ApiLocationsCitiesRoute
  '/api/locations/states': typeof ApiLocationsStatesRoute
  '/api/public-data/sources': typeof ApiPublicDataSourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculadora-assinaturas'
    | '/calculadora-conta-de-luz'
    | '/calculadora-custo-carro'
    | '/calculadora-custo-mudanca'
    | '/calculadora-custo-pet'
    | '/calculadora-morar-sozinho'
    | '/calculadoras'
    | '/comparar'
    | '/contato'
    | '/metodologia'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/api/energy-tariffs'
    | '/api/fuel-prices'
    | '/api/health'
    | '/api/vehicle-efficiency'
    | '/blog/assinaturas-que-valem-a-pena'
    | '/blog/como-economizar-conta-de-luz'
    | '/blog/custo-pet-anual'
    | '/blog/quanto-custa-morar-sozinho'
    | '/blog/quanto-custa-ter-carro'
    | '/comparar/academia'
    | '/comparar/energia'
    | '/comparar/mudanca'
    | '/comparar/streaming'
    | '/api/locations/cities'
    | '/api/locations/states'
    | '/api/public-data/sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculadora-assinaturas'
    | '/calculadora-conta-de-luz'
    | '/calculadora-custo-carro'
    | '/calculadora-custo-mudanca'
    | '/calculadora-custo-pet'
    | '/calculadora-morar-sozinho'
    | '/calculadoras'
    | '/comparar'
    | '/contato'
    | '/metodologia'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/api/energy-tariffs'
    | '/api/fuel-prices'
    | '/api/health'
    | '/api/vehicle-efficiency'
    | '/blog/assinaturas-que-valem-a-pena'
    | '/blog/como-economizar-conta-de-luz'
    | '/blog/custo-pet-anual'
    | '/blog/quanto-custa-morar-sozinho'
    | '/blog/quanto-custa-ter-carro'
    | '/comparar/academia'
    | '/comparar/energia'
    | '/comparar/mudanca'
    | '/comparar/streaming'
    | '/api/locations/cities'
    | '/api/locations/states'
    | '/api/public-data/sources'
  id:
    | '__root__'
    | '/'
    | '/calculadora-assinaturas'
    | '/calculadora-conta-de-luz'
    | '/calculadora-custo-carro'
    | '/calculadora-custo-mudanca'
    | '/calculadora-custo-pet'
    | '/calculadora-morar-sozinho'
    | '/calculadoras'
    | '/comparar'
    | '/contato'
    | '/metodologia'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/api/energy-tariffs'
    | '/api/fuel-prices'
    | '/api/health'
    | '/api/vehicle-efficiency'
    | '/blog/assinaturas-que-valem-a-pena'
    | '/blog/como-economizar-conta-de-luz'
    | '/blog/custo-pet-anual'
    | '/blog/quanto-custa-morar-sozinho'
    | '/blog/quanto-custa-ter-carro'
    | '/comparar/academia'
    | '/comparar/energia'
    | '/comparar/mudanca'
    | '/comparar/streaming'
    | '/api/locations/cities'
    | '/api/locations/states'
    | '/api/public-data/sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculadoraAssinaturasRoute: typeof CalculadoraAssinaturasRoute
  CalculadoraContaDeLuzRoute: typeof CalculadoraContaDeLuzRoute
  CalculadoraCustoCarroRoute: typeof CalculadoraCustoCarroRoute
  CalculadoraCustoMudancaRoute: typeof CalculadoraCustoMudancaRoute
  CalculadoraCustoPetRoute: typeof CalculadoraCustoPetRoute
  CalculadoraMorarSozinhoRoute: typeof CalculadoraMorarSozinhoRoute
  CalculadorasRoute: typeof CalculadorasRoute
  CompararRoute: typeof CompararRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  MetodologiaRoute: typeof MetodologiaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  ApiEnergyTariffsRoute: typeof ApiEnergyTariffsRoute
  ApiFuelPricesRoute: typeof ApiFuelPricesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiVehicleEfficiencyRoute: typeof ApiVehicleEfficiencyRoute
  BlogAssinaturasQueValemAPenaRoute: typeof BlogAssinaturasQueValemAPenaRoute
  BlogComoEconomizarContaDeLuzRoute: typeof BlogComoEconomizarContaDeLuzRoute
  BlogCustoPetAnualRoute: typeof BlogCustoPetAnualRoute
  BlogQuantoCustaMorarSozinhoRoute: typeof BlogQuantoCustaMorarSozinhoRoute
  BlogQuantoCustaTerCarroRoute: typeof BlogQuantoCustaTerCarroRoute
  ApiLocationsCitiesRoute: typeof ApiLocationsCitiesRoute
  ApiLocationsStatesRoute: typeof ApiLocationsStatesRoute
  ApiPublicDataSourcesRoute: typeof ApiPublicDataSourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras': {
      id: '/calculadoras'
      path: '/calculadoras'
      fullPath: '/calculadoras'
      preLoaderRoute: typeof CalculadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-morar-sozinho': {
      id: '/calculadora-morar-sozinho'
      path: '/calculadora-morar-sozinho'
      fullPath: '/calculadora-morar-sozinho'
      preLoaderRoute: typeof CalculadoraMorarSozinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-custo-pet': {
      id: '/calculadora-custo-pet'
      path: '/calculadora-custo-pet'
      fullPath: '/calculadora-custo-pet'
      preLoaderRoute: typeof CalculadoraCustoPetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-custo-mudanca': {
      id: '/calculadora-custo-mudanca'
      path: '/calculadora-custo-mudanca'
      fullPath: '/calculadora-custo-mudanca'
      preLoaderRoute: typeof CalculadoraCustoMudancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-custo-carro': {
      id: '/calculadora-custo-carro'
      path: '/calculadora-custo-carro'
      fullPath: '/calculadora-custo-carro'
      preLoaderRoute: typeof CalculadoraCustoCarroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-conta-de-luz': {
      id: '/calculadora-conta-de-luz'
      path: '/calculadora-conta-de-luz'
      fullPath: '/calculadora-conta-de-luz'
      preLoaderRoute: typeof CalculadoraContaDeLuzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-assinaturas': {
      id: '/calculadora-assinaturas'
      path: '/calculadora-assinaturas'
      fullPath: '/calculadora-assinaturas'
      preLoaderRoute: typeof CalculadoraAssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar/streaming': {
      id: '/comparar/streaming'
      path: '/streaming'
      fullPath: '/comparar/streaming'
      preLoaderRoute: typeof CompararStreamingRouteImport
      parentRoute: typeof CompararRoute
    }
    '/comparar/mudanca': {
      id: '/comparar/mudanca'
      path: '/mudanca'
      fullPath: '/comparar/mudanca'
      preLoaderRoute: typeof CompararMudancaRouteImport
      parentRoute: typeof CompararRoute
    }
    '/comparar/energia': {
      id: '/comparar/energia'
      path: '/energia'
      fullPath: '/comparar/energia'
      preLoaderRoute: typeof CompararEnergiaRouteImport
      parentRoute: typeof CompararRoute
    }
    '/comparar/academia': {
      id: '/comparar/academia'
      path: '/academia'
      fullPath: '/comparar/academia'
      preLoaderRoute: typeof CompararAcademiaRouteImport
      parentRoute: typeof CompararRoute
    }
    '/blog/quanto-custa-ter-carro': {
      id: '/blog/quanto-custa-ter-carro'
      path: '/blog/quanto-custa-ter-carro'
      fullPath: '/blog/quanto-custa-ter-carro'
      preLoaderRoute: typeof BlogQuantoCustaTerCarroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/quanto-custa-morar-sozinho': {
      id: '/blog/quanto-custa-morar-sozinho'
      path: '/blog/quanto-custa-morar-sozinho'
      fullPath: '/blog/quanto-custa-morar-sozinho'
      preLoaderRoute: typeof BlogQuantoCustaMorarSozinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/custo-pet-anual': {
      id: '/blog/custo-pet-anual'
      path: '/blog/custo-pet-anual'
      fullPath: '/blog/custo-pet-anual'
      preLoaderRoute: typeof BlogCustoPetAnualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/como-economizar-conta-de-luz': {
      id: '/blog/como-economizar-conta-de-luz'
      path: '/blog/como-economizar-conta-de-luz'
      fullPath: '/blog/como-economizar-conta-de-luz'
      preLoaderRoute: typeof BlogComoEconomizarContaDeLuzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/assinaturas-que-valem-a-pena': {
      id: '/blog/assinaturas-que-valem-a-pena'
      path: '/blog/assinaturas-que-valem-a-pena'
      fullPath: '/blog/assinaturas-que-valem-a-pena'
      preLoaderRoute: typeof BlogAssinaturasQueValemAPenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vehicle-efficiency': {
      id: '/api/vehicle-efficiency'
      path: '/api/vehicle-efficiency'
      fullPath: '/api/vehicle-efficiency'
      preLoaderRoute: typeof ApiVehicleEfficiencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fuel-prices': {
      id: '/api/fuel-prices'
      path: '/api/fuel-prices'
      fullPath: '/api/fuel-prices'
      preLoaderRoute: typeof ApiFuelPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/energy-tariffs': {
      id: '/api/energy-tariffs'
      path: '/api/energy-tariffs'
      fullPath: '/api/energy-tariffs'
      preLoaderRoute: typeof ApiEnergyTariffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-data/sources': {
      id: '/api/public-data/sources'
      path: '/api/public-data/sources'
      fullPath: '/api/public-data/sources'
      preLoaderRoute: typeof ApiPublicDataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/locations/states': {
      id: '/api/locations/states'
      path: '/api/locations/states'
      fullPath: '/api/locations/states'
      preLoaderRoute: typeof ApiLocationsStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/locations/cities': {
      id: '/api/locations/cities'
      path: '/api/locations/cities'
      fullPath: '/api/locations/cities'
      preLoaderRoute: typeof ApiLocationsCitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompararRouteChildren {
  CompararAcademiaRoute: typeof CompararAcademiaRoute
  CompararEnergiaRoute: typeof CompararEnergiaRoute
  CompararMudancaRoute: typeof CompararMudancaRoute
  CompararStreamingRoute: typeof CompararStreamingRoute
}

const CompararRouteChildren: CompararRouteChildren = {
  CompararAcademiaRoute: CompararAcademiaRoute,
  CompararEnergiaRoute: CompararEnergiaRoute,
  CompararMudancaRoute: CompararMudancaRoute,
  CompararStreamingRoute: CompararStreamingRoute,
}

const CompararRouteWithChildren = CompararRoute._addFileChildren(
  CompararRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculadoraAssinaturasRoute: CalculadoraAssinaturasRoute,
  CalculadoraContaDeLuzRoute: CalculadoraContaDeLuzRoute,
  CalculadoraCustoCarroRoute: CalculadoraCustoCarroRoute,
  CalculadoraCustoMudancaRoute: CalculadoraCustoMudancaRoute,
  CalculadoraCustoPetRoute: CalculadoraCustoPetRoute,
  CalculadoraMorarSozinhoRoute: CalculadoraMorarSozinhoRoute,
  CalculadorasRoute: CalculadorasRoute,
  CompararRoute: CompararRouteWithChildren,
  ContatoRoute: ContatoRoute,
  MetodologiaRoute: MetodologiaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  ApiEnergyTariffsRoute: ApiEnergyTariffsRoute,
  ApiFuelPricesRoute: ApiFuelPricesRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiVehicleEfficiencyRoute: ApiVehicleEfficiencyRoute,
  BlogAssinaturasQueValemAPenaRoute: BlogAssinaturasQueValemAPenaRoute,
  BlogComoEconomizarContaDeLuzRoute: BlogComoEconomizarContaDeLuzRoute,
  BlogCustoPetAnualRoute: BlogCustoPetAnualRoute,
  BlogQuantoCustaMorarSozinhoRoute: BlogQuantoCustaMorarSozinhoRoute,
  BlogQuantoCustaTerCarroRoute: BlogQuantoCustaTerCarroRoute,
  ApiLocationsCitiesRoute: ApiLocationsCitiesRoute,
  ApiLocationsStatesRoute: ApiLocationsStatesRoute,
  ApiPublicDataSourcesRoute: ApiPublicDataSourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
